// Реэкспорт типов ролей для обратной совместимости
export type { UiRole, EmployeeRole, ApiRole } from '@/shared/types/roles.types'

export type Tab =
  | 'home'
  | 'shifts'
  | 'notifications'
  | 'profile'
  | 'vacancies'
  | 'exchange'
  | 'suppliers'
  | 'myshifts'
  | 'staff'
  | 'requests'
  | 'showcase'
  | 'feed'
  | 'activity'

export type Screen =
  | 'loading'
  | 'home'
  | 'shifts'
  | 'vacancies'
  | 'profile'
  | 'notifications'
  | 'create-shift'
  | 'settings'
  | 'suppliers'
  | 'find-replacement'
  | 'work-management'
  | 'applications'
