import type { useFeedPageModel } from './hooks/useFeedPageModel'

export type ProfileAlertState = ReturnType<typeof useFeedPageModel>['profileAlert']

/** View-model для FeedBody — подмножество полей useFeedPageModel. */
export type FeedBodyVm = Pick<
  ReturnType<typeof useFeedPageModel>,
  | 'feedType'
  | 'filteredShifts'
  | 'activeList'
  | 'onRefresh'
  | 'openShiftDetails'
  | 'openRestaurantDetails'
  | 'getApplicationId'
  | 'getApplicationStatus'
  | 'isApplied'
  | 'handleApplyWithModal'
  | 'isApplyCoverModalOpen'
  | 'isApplyCoverModalSubmitting'
  | 'applyCoverShift'
  | 'userProfile'
  | 'closeApplyCoverModal'
  | 'submitApplyCoverModal'
  | 'applicationSuccess'
  | 'applicationSuccessShift'
  | 'closeApplicationSuccess'
  | 'openApplicationsAfterApply'
  | 'searchMoreAfterApply'
  | 'handleCancel'
  | 'isShiftLoading'
  | 'handleEdit'
  | 'handleDelete'
  | 'isDeleting'
  | 'selectedShiftId'
  | 'selectedRestaurantId'
  | 'selectedShift'
  | 'selectedVacancy'
  | 'closeShiftDetails'
  | 'closeRestaurantDetails'
  | 'toast'
  | 'hideToast'
  | 'hasActiveFilters'
  | 'emptyMessage'
  | 'emptyDescription'
  | 'resetFilters'
  | 'profileAlert'
  | 'closeProfileAlert'
  | 'openProfileEdit'
  | 'isFiltersOpen'
  | 'closeFilters'
  | 'applyAdvancedFilters'
  | 'advancedFilters'
  | 'resetFeedFilters'
  | 'isVacancy'
>
